/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import model.bean.Cliente;
import model.dao.ClienteDAO;
import static view.TelaCliente.btnEditar;
import static view.TelaCliente.btnExcluir;
import static view.TelaCliente.btnImprimir;
import static view.TelaCliente.cbUF;
import static view.TelaCliente.cbxInativo;
import static view.TelaCliente.ftxtCelular;
import static view.TelaCliente.txtBairro;
import static view.TelaCliente.txtCep;
import static view.TelaCliente.txtCgc;
import static view.TelaCliente.txtCidade;
import static view.TelaCliente.txtComplemento;
import static view.TelaCliente.txtDataCadastro;
import static view.TelaCliente.txtEmail;
import static view.TelaCliente.txtEndereco;
import static view.TelaCliente.txtId;
import static view.TelaCliente.txtNome;
import static view.TelaCliente.txtNumero;
import static view.TelaCliente.txtOpCadastro;
import static view.TelaCliente.txtTelefone;

/**
 *
 * @author marlon
 */
public class TelaPesquisaCli extends javax.swing.JDialog {

    /**
     * Creates new form TelaPesquisaProd
     *
     * @param parent
     * @param modal
     */
    public TelaPesquisaCli(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public static boolean telaPesquisaProd;
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        precoRender1 = new util.PrecoRender();
        cbxPesq = new javax.swing.JComboBox<>();
        txtPesquisaCli = new javax.swing.JTextField();
        btnPesqCli = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCli = new javax.swing.JTable();
        btnSair = new javax.swing.JToggleButton();
        btnSelecionar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Produto");
        setMinimumSize(new java.awt.Dimension(690, 485));
        setModal(true);
        setResizable(false);

        cbxPesq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CGC", "NOME" }));

        txtPesquisaCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaCliKeyPressed(evt);
            }
        });

        btnPesqCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons24/icons8-pesquisar-24.png"))); // NOI18N
        btnPesqCli.setText("Pesquisar");
        btnPesqCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqCliActionPerformed(evt);
            }
        });

        jTableCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Condigo", "CGC", "Nome", "Celular", "Cidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCli.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTableCliAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTableCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCliMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableCliMouseEntered(evt);
            }
        });
        jTableCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableCliKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCli);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons24/icons8-desligar-24.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons24/icons8-ok-24.png"))); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(precoRender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(774, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSair)
                            .addGap(18, 18, 18)
                            .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbxPesq, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(txtPesquisaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnPesqCli)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(412, Short.MAX_VALUE)
                .addComponent(precoRender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPesquisaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesqCli))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSelecionar)
                        .addComponent(btnSair))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaCliKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            parametroPesquisa();

        }
    }//GEN-LAST:event_txtPesquisaCliKeyPressed

    private void btnPesqCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqCliActionPerformed
        // TODO add your handling code here:
        parametroPesquisa();

    }//GEN-LAST:event_btnPesqCliActionPerformed

    private void jTableCliAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTableCliAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableCliAncestorAdded

    private void jTableCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCliMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            setar();
            dispose();

        }

    }//GEN-LAST:event_jTableCliMouseClicked

    private void jTableCliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCliMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableCliMouseEntered

    private void jTableCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableCliKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            setar();
            //conCli = false;
            dispose();
            //ativarcampos();

        }
    }//GEN-LAST:event_jTableCliKeyPressed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        TelaCliente.conCli = false;
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        // TODO add your handling code here:
        setar();
        //conCli = false;
        dispose();
        // ativarcampos();
    }//GEN-LAST:event_btnSelecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPesquisaCli dialog = new TelaPesquisaCli(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesqCli;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JToggleButton btnSelecionar;
    private javax.swing.JComboBox<String> cbxPesq;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableCli;
    private util.PrecoRender precoRender1;
    public static javax.swing.JTextField txtPesquisaCli;
    // End of variables declaration//GEN-END:variables

    public void readCgc() {

        DefaultTableModel modelo = (DefaultTableModel) jTableCli.getModel();
        modelo.setNumRows(0);
        ClienteDAO dao = new ClienteDAO();

        String id = txtPesquisaCli.getText();

        dao.findByCgc(id).forEach((Cliente c) -> {
            modelo.addRow(new Object[]{
                c.getIdCliente(),
                c.getCgc(),
                c.getNome(),
                c.getCelular(),
                c.getCidade()

            });
        });

    }

    public void readNome() {

        DefaultTableModel modelo = (DefaultTableModel) jTableCli.getModel();
        modelo.setNumRows(0);
        ClienteDAO dao = new ClienteDAO();

        String nome = txtPesquisaCli.getText();

        dao.findByNome(nome).forEach((Cliente c) -> {
            modelo.addRow(new Object[]{
                c.getIdCliente(),
                c.getCgc(),
                c.getNome(),
                c.getCelular(),
                c.getCidade()

            });
        });

    }

    public void readCod() {

        DefaultTableModel modelo = (DefaultTableModel) jTableCli.getModel();
        modelo.setNumRows(0);
        ClienteDAO dao = new ClienteDAO();

        String nome = txtPesquisaCli.getText();

        dao.findByCod(nome).forEach((Cliente c) -> {
            modelo.addRow(new Object[]{
                c.getIdCliente(),
                c.getCgc(),
                c.getNome(),
                c.getCelular(),
                c.getCidade()

            });
        });
    }
    
    private void parametroPesquisa(){
        
         if(cbxPesq.getSelectedItem() == "CGC"){
            readCgc();
        }if(cbxPesq.getSelectedItem() == "NOME"){
            readNome();            
        }
        
    }
    
    private void setar() {

        ClienteDAO dao = new ClienteDAO();

        Integer id = (Integer) jTableCli.getValueAt(jTableCli.getSelectedRow(), 0);

        Cliente c = dao.findById(id);

        System.out.println(c.getNome());

        txtId.setText(String.valueOf(c.getIdCliente()));
        txtCgc.setText(c.getCgc());
        txtNome.setText(c.getNome());
        ftxtCelular.setText(c.getCelular());
        txtTelefone.setText(c.getTelefone());
        txtEmail.setText(c.getEmail());
        txtCep.setText(c.getCep());
        txtEndereco.setText(c.getEndereco());
        txtComplemento.setText(c.getComplemento());
        txtNumero.setText(c.getNumero());
        txtBairro.setText(c.getBairro());
        txtCidade.setText(c.getCidade());
        cbUF.setSelectedItem(c.getUf());

        cbxInativo.setSelected(c.getInativo());

        if (c.getDatacadastro() != null) {
            txtDataCadastro.setText(sdf.format(c.getDatacadastro()));
            txtOpCadastro.setText(c.getOperadorcadastro());
        } else {
            txtDataCadastro.setText("");
            txtOpCadastro.setText("");
        }
        
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnImprimir.setEnabled(true);
        
    }

}
