/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Embalagem;
import model.dao.EmbalagemDAO;

/**
 *
 * @author Marlon
 */
public class TelaEmbalagem extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMarca
     */
    public TelaEmbalagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbEmbalagens = new javax.swing.JTable();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtEmbalagem = new javax.swing.JTextField();

        setResizable(true);
        setTitle("Cadastro de Embalagens");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Codigo");

        txtCodigo.setEditable(false);

        jLabel2.setText("Descrição");

        jtbEmbalagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Embalagem", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbEmbalagens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbEmbalagensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbEmbalagens);
        if (jtbEmbalagens.getColumnModel().getColumnCount() > 0) {
            jtbEmbalagens.getColumnModel().getColumn(0).setMinWidth(90);
            jtbEmbalagens.getColumnModel().getColumn(0).setPreferredWidth(90);
            jtbEmbalagens.getColumnModel().getColumn(0).setMaxWidth(90);
            jtbEmbalagens.getColumnModel().getColumn(1).setMinWidth(100);
            jtbEmbalagens.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtbEmbalagens.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons18/icons8-salvar-18.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons18/icons8-adicionar-arquivo-18.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons18/icons8-cancelar-2-18.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons18/icons8-apagar-para-sempre-18.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel3.setText("Embalagem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(txtEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnExcluir)
                            .addGap(12, 12, 12)
                            .addComponent(btnNovo)
                            .addGap(18, 18, 18)
                            .addComponent(btnSalvar)
                            .addGap(18, 18, 18)
                            .addComponent(btnSair))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnSalvar)
                    .addComponent(btnNovo)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:

        if (txtDescricao.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Preencha Todos o Caompo Descrição !");

        } else {

            if (txtCodigo.getText().isEmpty()) {

                btnsalvar();
                readTableEmbalagem();

                // BOTÕES
                // btnDesativar.setEnabled(true);
                //btnSalvar.setEnabled(true);
                //btnNovo.setEnabled(true);
            } else {
                btnupdate();
                readTableEmbalagem();
            }

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jtbEmbalagensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbEmbalagensMouseClicked
        // TODO add your handling code here:

        setar();
    }//GEN-LAST:event_jtbEmbalagensMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        readTableEmbalagem();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

        btnexcluir();
        readTableEmbalagem();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:

        dispose();
        JfPrincipal.cadEmbalagem = false;
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:

        txtCodigo.setText(null);
        txtEmbalagem.setText(null);
        txtDescricao.setText(null);

        txtEmbalagem.requestFocus();


    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtCodigo.setText(null);
        txtEmbalagem.setText(null);
        txtDescricao.setText(null);

        txtEmbalagem.requestFocus();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void btnupdate() {

        EmbalagemDAO dao = new EmbalagemDAO();

        Embalagem e = new Embalagem();

        e.setCodigo(Integer.parseInt(txtCodigo.getText()));
        e.setEmbalagem(txtEmbalagem.getText());
        e.setDescricao(txtDescricao.getText());

        dao.update(e);

        txtCodigo.setText(null);
        txtEmbalagem.setText(null);
        txtDescricao.setText(null);

    }

    public void readTableEmbalagem() {

        DefaultTableModel modelo = (DefaultTableModel) jtbEmbalagens.getModel();
        modelo.setNumRows(0);
        EmbalagemDAO dao = new EmbalagemDAO();

        dao.readEmbalagem().forEach((e) -> {
            modelo.addRow(new Object[]{
                e.getCodigo(),
                e.getEmbalagem(),
                e.getDescricao()});
        });

    }

    public void btnsalvar() {

        EmbalagemDAO dao = new EmbalagemDAO();

        Embalagem e = new Embalagem();

        e.setEmbalagem(txtEmbalagem.getText());
        e.setDescricao(txtDescricao.getText());

        dao.save(e);

        txtCodigo.setText(String.valueOf(e.getCodigo()));
        txtEmbalagem.setText(e.getEmbalagem());
        txtDescricao.setText(e.getDescricao());

        txtEmbalagem.requestFocus();

    }

    public void setar() {

        EmbalagemDAO dao = new EmbalagemDAO();

        Integer id = (Integer) jtbEmbalagens.getValueAt(jtbEmbalagens.getSelectedRow(), 0);

        Embalagem e = dao.findById(id);

        txtCodigo.setText(String.valueOf(e.getCodigo()));
        txtEmbalagem.setText(e.getEmbalagem());
        txtDescricao.setText(e.getDescricao());

    }

    public void btnexcluir() {

        EmbalagemDAO dao = new EmbalagemDAO();

        Embalagem e = new Embalagem();

        e.setCodigo(Integer.parseInt(txtCodigo.getText()));

        Integer id = (Integer) jtbEmbalagens.getValueAt(jtbEmbalagens.getSelectedRow(), 0);

        dao.remove(id);

        txtCodigo.setText(null);
        txtEmbalagem.setText(null);
        txtDescricao.setText(null);

        txtEmbalagem.requestFocus();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jtbEmbalagens;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEmbalagem;
    // End of variables declaration//GEN-END:variables
}
